# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80bc63ae216b6584c241db077634740150821ea7522e7a15d9a80698945584f1d4bf0496eb054d3167f12f814437f4b24cc312397df371f70164c76093d4b98a

test:
  secret_key_base: 3b6d60a7b92f5a2689f5a98abdbe39dae5e001034cb9af4272063a08909c2779c145c7dffeaeb84f19e8836707619422dd6f8f654c31b14326d4fd54ab4bc941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
